# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['mewgenics_manager.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('mewgenics/utils/locales/en.json', '.'),
        ('mewgenics/utils/locales/ru.json', '.'),
        ('mewgenics/utils/locales/zh_CN.json', '.'),
        ('mewgenics/utils/locales/pl.json', '.'),
        ('../VERSION', '.'),
    ],
    hiddenimports=[
        'lz4.frame',
        'lz4.block',
        'visual_mutation_catalog',
        'mewgenics',
        'mewgenics.app',
        'mewgenics.main_window',
        'mewgenics.constants',
        'mewgenics.dialogs',
        'mewgenics.utils',
        'mewgenics.utils.paths',
        'mewgenics.utils.config',
        'mewgenics.utils.localization',
        'mewgenics.utils.styling',
        'mewgenics.utils.tags',
        'mewgenics.utils.thresholds',
        'mewgenics.utils.optimizer_settings',
        'mewgenics.utils.planner_state',
        'mewgenics.utils.game_data',
        'mewgenics.utils.calibration',
        'mewgenics.utils.cat_persistence',
        'mewgenics.utils.cat_analysis',
        'mewgenics.utils.abilities',
        'mewgenics.utils.table_state',
        'mewgenics.models',
        'mewgenics.models.breeding_cache',
        'mewgenics.models.cat_table_model',
        'mewgenics.models.room_filter_model',
        'mewgenics.workers',
        'mewgenics.workers.save_loader',
        'mewgenics.workers.room_refresh',
        'mewgenics.workers.optimizer_worker',
        'mewgenics.panels',
        'mewgenics.panels.cat_detail',
        'mewgenics.panels.room_priority',
        'mewgenics.views',
        'mewgenics.views.family_tree',
        'mewgenics.views.safe_breeding',
        'mewgenics.views.breeding_partners',
        'mewgenics.views.room_optimizer',
        'mewgenics.views.perfect_planner',
        'mewgenics.views.calibration',
        'mewgenics.views.mutation_planner',
        'mewgenics.views.furniture',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='MewgenicsManager',
    onefile=True,
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,   # no console window
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
